// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_codegen.cpp:148

#ifndef _TAO_IDL_BANKC_4QSEXS_H_
#define _TAO_IDL_BANKC_4QSEXS_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 4 || TAO_MINOR_VERSION != 0 || TAO_MICRO_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_root\root_ch.cpp:155


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_module\module_ch.cpp:34

namespace Bank
{
  // TAO_IDL - Generated from
  // C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_BANK_TRANSACTION__VAR_OUT_CH_)
#define _BANK_TRANSACTION__VAR_OUT_CH_

  class Transaction;
  using Transaction_ptr = Transaction*;
  using Transaction_var = TAO_Objref_Var_T<Transaction>;
  using Transaction_out = TAO_Objref_Out_T<Transaction>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  Transaction
    : public virtual ::CORBA::Object
  {
  public:
    friend class TAO::Narrow_Utils<Transaction>;
    // TAO_IDL - Generated from
    // C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = Transaction_ptr;
    using _var_type = Transaction_var;
    using _out_type = Transaction_out;

    static void _tao_any_destructor (void *);

    // The static operations.
    static Transaction_ptr _duplicate (Transaction_ptr obj);

    static void _tao_release (Transaction_ptr obj);

    static Transaction_ptr _narrow (::CORBA::Object_ptr obj);
    static Transaction_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static Transaction_ptr _nil ();

    virtual char * updateDetails (
      const char * counterId,
      const char * date,
      ::CORBA::Double amountDebit,
      ::CORBA::Double amountCredit,
      const char * accountId);

    
    // TAO_IDL - Generated from
    // C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    Transaction ();

    // Concrete non-local interface only.
    Transaction (::IOP::IOR *ior, TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    Transaction (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = nullptr,
        TAO_ORB_Core *orb_core = nullptr);

    virtual ~Transaction () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    Transaction (const Transaction &) = delete;
    Transaction (Transaction &&) = delete;
    Transaction &operator= (const Transaction &) = delete;
    Transaction &operator= (Transaction &&) = delete;
  };
  // TAO_IDL - Generated from
  // C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_typecode\typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_Transaction;


// TAO_IDL - Generated from
// C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_module\module_ch.cpp:62


} // module Bank
// TAO_IDL - Generated from
// C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_arg_traits.cpp:142

  

#if !defined (_BANK_TRANSACTION__ARG_TRAITS_)
#define _BANK_TRANSACTION__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::Bank::Transaction>
    : public Object_Arg_Traits_T<
        ::Bank::Transaction_ptr,
        ::Bank::Transaction_var,
        ::Bank::Transaction_out,
        TAO::Objref_Traits<Bank::Transaction>,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_BANK_TRANSACTION__TRAITS_)
#define _BANK_TRANSACTION__TRAITS_

  template<>
  struct  Objref_Traits< ::Bank::Transaction>
  {
    static ::Bank::Transaction_ptr duplicate (::Bank::Transaction_ptr p);
    static void release (::Bank::Transaction_ptr p);
    static ::Bank::Transaction_ptr nil ();
    static ::CORBA::Boolean marshal (const ::Bank::Transaction_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\any_op_ch.cpp:40




TAO_BEGIN_VERSIONED_NAMESPACE_DECL
namespace CORBA {

 void operator<<= (::CORBA::Any &, Bank::Transaction_ptr); // copying
 void operator<<= (::CORBA::Any &, Bank::Transaction_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Bank::Transaction_ptr &);
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_visitor_interface\cdr_op_ch.cpp:40



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Bank::Transaction_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, Bank::Transaction_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// C:\Users\hp\Desktop\yassir\Softwars\libraries\ACE_TAO\ACE_wrappers\TAO\TAO_IDL\be\be_codegen.cpp:1648

#if defined (__ACE_INLINE__)
#include "bankC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

